jQuery(document).ready(function(){'use strict';$(window).on('load',function(){$('#preloader').fadeOut(500);});$('.select-drop').selectbox();$(window).on('load',function(){$('#body').each(function(){var header_area=$('.nav-wrapper');var main_area=header_area.find('.navbar');var main_area_fullwidth=$('.navbar.navbar-fullwidth');$(window).scroll(function(){if(main_area.hasClass('navbar-sticky')&&($(this).scrollTop()<=400||$(this).width()<=750)){main_area.removeClass('navbar-sticky').appendTo(header_area);}else if(!main_area.hasClass('navbar-sticky')&&$(this).width()>750&&$(this).scrollTop()>400){header_area.css('height',header_area.height());main_area.css({'opacity':'0'}).addClass('navbar-sticky');main_area.appendTo($('body')).animate({'opacity':1});}});});});$('.navbar a.dropdown-toggle').on('click',function(e){var elmnt=$(this).parent().parent();if(!elmnt.hasClass('nav')){var li=$(this).parent();var heightParent=parseInt(elmnt.css('height').replace('px',''))/2;var widthParent=parseInt(elmnt.css('width').replace('px',''))-10;if(!li.hasClass('open')){li.addClass('open');}
else{li.removeClass('open');$(this).next().css('top',heightParent+'px');$(this).next().css('left',widthParent+'px');}
return false;}});if($('.navbar').width()>1007)
{$('.nav .dropdown').hover(function(){$(this).addClass('open');},function(){$(this).removeClass('open');});}
$('.scrolling  a[href*="#"]').on('click',function(e){e.preventDefault();e.stopPropagation();var target=$(this).attr('href');$(target).velocity('scroll',{duration:800,offset:-150,easing:'easeOutExpo',mobileHA:false});});$('.scrolling').click(function(){$('html, body').animate({scrollTop:$('#message').offset().top-50},600);});(function(){$('#thubmnailSlider').carousel({interval:3000});}());(function(){$('.thumbnailCarousel .item').each(function(){var itemToClone=$(this);var i=1;if($(window).width()<=767){for(i=1;i<1;i++){itemToClone=itemToClone.next();if(!itemToClone.length){itemToClone=$(this).siblings(':first');}
itemToClone.children(':first-child').clone().addClass('cloneditem-'+(i)).appendTo($(this));}}else if($(window).width()<=991){for(i=1;i<2;i++){itemToClone=itemToClone.next();if(!itemToClone.length){itemToClone=$(this).siblings(':first');}
itemToClone.children(':first-child').clone().addClass('cloneditem-'+(i)).appendTo($(this));}}else{for(i=1;i<3;i++){itemToClone=itemToClone.next();if(!itemToClone.length){itemToClone=$(this).siblings(':first');}
itemToClone.children(':first-child').clone().addClass('cloneditem-'+(i)).appendTo($(this));}}});}());$('.counter').counterUp({delay:10,time:2000});$('.datepicker').datepicker({startDate:'dateToday',autoclose:true});$(document).on('click','.browse',function(){var file=$(this).parent().parent().parent().find('.file');file.trigger('click');});var $heroSlider=$('.main-slider .inner');if($heroSlider.length>0){$heroSlider.each(function(){var loop=$(this).parent().data('loop'),autoplay=$(this).parent().data('autoplay'),interval=$(this).parent().data('interval')||3000;$(this).owlCarousel({items:1,loop:loop,margin:0,nav:true,dots:false,navText:[],autoplay:autoplay,autoplayTimeout:interval,autoplayHoverPause:true,smartSpeed:700,});});}
var heroSlider2=$('.banner-home-city .owl-carousel');heroSlider2.owlCarousel({loop:true,items:1,nav:true,dots:false,autoplay:true,autoplayTimeOut:5000,navText:['<i class="fa fa-angle-left" aria-hidden="true"></i>','<i class="fa fa-angle-right " aria-hidden="true"></i>'],});var owl=$('.owl-carousel.partnersLogoSlider');owl.owlCarousel({loop:true,margin:28,autoplay:true,autoplayTimeout:6000,autoplayHoverPause:true,nav:true,dots:false,smartSpeed:500,responsive:{320:{slideBy:1,items:1},768:{slideBy:1,items:3},992:{slideBy:1,items:4}}});$('.testimonial-slider').owlCarousel({center:true,loop:true,autoplay:true,autoplayTimeout:6000,smartSpeed:1000,responsive:{320:{slideBy:1,items:1,},768:{slideBy:1,items:1},992:{slideBy:1,items:3}}});$('.quick_view').fancybox({baseClass:'quick-view-container',infobar:false,buttons:false,thumbs:false,margin:0,touch:{vertical:false},animationEffect:false,transitionEffect:'slide',transitionDuration:500,baseTpl:'<div class="fancybox-container" role="dialog">'+
'<div class="quick-view-content">'+
'<div class="quick-view-carousel">'+
'<div class="fancybox-stage"></div>'+
'</div>'+
'<div class="quick-view-aside"></div>'+
'<button data-fancybox-close class="quick-view-close">X</button>'+
'</div>'+
'</div>',onInit:function(instance){var bullets='<ul class="quick-view-bullets">';for(var i=0;i<instance.group.length;i++){bullets+='<li><a data-index="'+i+'" href="javascript:;"><span>'+(i+1)+'</span></a></li>';}
bullets+='</ul>';$(bullets).on('click touchstart','a',function(){var index=$(this).data('index');$.fancybox.getInstance(function(){this.jumpTo(index);});}).appendTo(instance.$refs.container.find('.quick-view-carousel'));var $element=instance.group[instance.currIndex].opts.$orig;var form_id=$element.data('qw-form');instance.$refs.container.find('.quick-view-aside').append($('#'+form_id).clone(true).removeClass('hidden'));},beforeShow:function(instance){instance.$refs.container.find('.quick-view-bullets').children().removeClass('active').eq(instance.currIndex).addClass('active');}});$('.close-btn').click(function(){$(this).parent().hide();});var grid=$('.gallery_grid');$('.grid').isotope({itemSelector:'.grid-item',layoutMode:'fitRows'});if(grid.length){grid.isotope({itemSelector:'.element',layoutMode:'fitRows'});$('#filters .button').on('click',function(){$('#filters .button').removeClass('active');$(this).addClass('active');var selector=$(this).attr('data-filter');$('.gallery_grid').isotope({filter:selector});return false;});}
$(".user-pro").rateYo({starWidth:"15px",spacing:"5px"});$(".visitor").rateYo({rating:3.2,readOnly:true,starWidth:"15px",spacing:"5px"});$(".user").rateYo({starWidth:"15px",spacing:"5px"});$('.fa-heart-o').on('click',function(){$(this).toggleClass('active');});});